name: clearpath_config_ci

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  build_and_test:
    name: jazzy
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: jazzy, ROS_REPO: testing}
          - {ROS_DISTRO: jazzy, ROS_REPO: main}
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

  clearpath_config_src_ci:
    name: Jazzy Clearpath Source
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: jazzy
